import pandas as pd
import numpy as np
a=pd.read_csv('C:/Users/Admin/Desktop/heart dv.csv')
print(a)
print(len(a))
print(a.columns)
print(a.info())
print(a.isnull())
print(a.shape)
print(a.head()) 
print(a.head(10))
print(a.tail())     
print(a.tail(10))
print(a.describe())
print(a.dtypes)
print(a['age'].value_counts())
print(a['sex'].value_counts())
print(a['cp'].value_counts())
print(a['trestbps'].value_counts())
print(a['chol'].value_counts())
print(a['fbs'].value_counts())
print(a['thalach'].value_counts())
print(a['oldpeak'].value_counts())
print(a.groupby('sex').agg(['min']))
print(a.groupby('sex').agg(['max']))
print(a.groupby('sex').agg(['mean']))
print(a.groupby('sex').agg(['median']))
print(a['trestbps'].mean())
print(a['trestbps'].max())
print(a['trestbps'].min())
print(a['trestbps'].count())
print(a['trestbps'].std())
print(a['trestbps'].unique())
print(a['trestbps'].nunique())
print(a['trestbps']*2)
print(a['oldpeak']+2)
print(a.isnull().sum())
a.rename(columns={'target':'Target'},inplace=True)
print(a.columns)
print(a.loc[:5,"age"])
sum1= a.groupby(['age']).sum()
print('Sum of values, grouped by the age: ' + str(sum1))
